#include "easy_config.h"

enum config_id {
	CONFIG_DEVICE_ID,
	CONIG_DEVICE_FRIENDLY_NAME,
	CONFIG_HAS_BATTERY,
	CONFIG_SLEEP_INTERVAL,

	CONFIG_USE_INFLUX,
	CONFIG_INFLUX_USERNAME,
	CONFIG_INFLUX_PASSWORD,
	
	CONFIG_USE_MQTT,
	CONFIG_MQTT_URI,

	/* todo: uhhhhhhhhh */
	CONFIG_WIFI_SSID_1,
	CONFIG_WIFI_PSK_1,
	CONFIG_WIFI_SSID_2,
	CONFIG_WIFI_PSK_2,
	CONFIG_END
};